FROM node:22-alpine AS builder

WORKDIR /app

COPY apps/public-app/package*.json ./
RUN npm ci

COPY apps/public-app/ ./

RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3002

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3002

CMD ["node", "server.js"]
