import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb786",
        "on-tertiary-container": "#461f00",
        "on-secondary-fixed-variant": "#004e5c",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        background: "#10131a",
        "tertiary-fixed": "#ffdcc6",
        "on-surface-variant": "#c2c6d6",
        "on-primary-fixed": "#001a42",
        "on-tertiary-fixed-variant": "#723600",
        "surface-variant": "#32353c",
        "inverse-primary": "#005ac2",
        error: "#ffb4ab",
        "on-secondary-container": "#00424e",
        "surface-dim": "#10131a",
        "on-tertiary-fixed": "#311400",
        "surface-container-low": "#191b23",
        "on-primary": "#002e6a",
        "inverse-on-surface": "#2e3038",
        "surface-container-lowest": "#0b0e15",
        primary: "#adc6ff",
        "on-tertiary": "#502400",
        "outline-variant": "#424754",
        "secondary-container": "#03b5d4",
        "primary-container": "#4d8eff",
        "on-error": "#690005",
        "surface-container-highest": "#32353c",
        "secondary-fixed": "#acedff",
        "surface-tint": "#adc6ff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-primary-container": "#00285d",
        "on-error-container": "#ffdad6",
        "surface-container": "#1d2027",
        "surface-bright": "#363941",
        surface: "#10131a",
        outline: "#8c909f",
        "inverse-surface": "#e1e2ec",
        "surface-container-high": "#272a31",
        "tertiary-container": "#df7412",
        secondary: "#4cd7f6",
        "on-secondary-fixed": "#001f26",
        "on-background": "#e1e2ec",
        "on-secondary": "#003640",
        "on-surface": "#e1e2ec",
        "error-container": "#93000a",
        tertiary: "#ffb786",
        "on-primary-fixed-variant": "#004395",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "8px",
        xs: "4px",
        xl: "32px",
        md: "16px",
        gutter: "16px",
        margin: "24px",
        lg: "24px",
      },
      fontFamily: {
        "title-sm": ["Inter"],
        "display-lg": ["Space Grotesk"],
        "body-sm": ["Inter"],
        "mono-data": ["monospace"],
        "label-caps": ["Inter"],
        "headline-md": ["Space Grotesk"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "title-sm": [
          "18px",
          { lineHeight: "1.4", fontWeight: "600" },
        ],
        "display-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-sm": [
          "13px",
          { lineHeight: "1.4", fontWeight: "400" },
        ],
        "mono-data": [
          "14px",
          { lineHeight: "1", letterSpacing: "0", fontWeight: "500" },
        ],
        "label-caps": [
          "11px",
          { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", fontWeight: "500" },
        ],
        "body-md": [
          "14px",
          { lineHeight: "1.5", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
